name: miss_admin
description: Miss IDE Admin Dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
  go_router: ^13.1.0
  http: ^1.2.0
  intl: ^0.19.0
  fl_chart: ^0.66.0
  data_table_2: ^2.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
